---
ID: "1c293067-a9cf-4a12-a533-5b3580ccb928"
Parent: "ebd498ba-a204-41e3-953d-94ced6cf775f"
Template: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Path: /sitecore/content/Demo Shared Standard Sites/Habitat Home Corporate/Settings/Security Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190131T214506Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f31dc041-5d18-49e9-b3d0-002de11207b6"
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: 
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: 
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190613T142121Z
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: 
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{52054874-4767-47DC-8099-8C08BFA307AA}"
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190409T150045Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8abab598-6a00-41ce-b365-3391270d2e5c"
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: 
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: 
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190613T142121Z
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: 
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{52054874-4767-47DC-8099-8C08BFA307AA}"
