trigger:
  branches:
    include:
    - feature/*
    - bug/*
    exclude:
    - master
    - release/*
    - integration/*

pool:
  name: DEVDEMO1US1
  demands:
  - msbuild

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'NuGet restore Solution'
  inputs:
    restoreSolution: HabitatHome.Corporate.sln
    feedsToUse: config
    nugetConfigPath: 'nuget.config'

- task: MSBuild@1
  displayName: 'HabitatHome.Corporate Build Solution'
  inputs:
    solution: HabitatHome.Corporate.sln
    configuration: 'Debug'
    msbuildArguments: '/m'