---
ID: "19c8427e-e1f8-4ee9-a5a5-f17b7b6f869e"
Parent: "9bcd885b-8b18-4ea5-aea1-bc5f918d5b90"
Template: "9bcd885b-8b18-4ea5-aea1-bc5f918d5b90"
Path: /sitecore/templates/Feature/Demo Shared/Components/Component/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{9BCD885B-8B18-4EA5-AEA1-BC5F918D5B90}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190102T192528Z
